### ISSUE TITLE
How to convert buffers to JSON?

### ISSUE THREAD

**Issue by range-of-motion** [hjdhjd/unifi-protect#3]
Hey there, thanks for creating this library.

I'm trying to detect doorbell rings and used this project to bootstrap the websocket. I'm currently able to retrieve messages, but they're encoded? I'm not very known with this, what is this? Is there an easy way to convert this to JSON? An example of my messages is below.

<img width="987" alt="Screenshot 2022-02-08 at 12 44 50" src="https://user-images.githubusercontent.com/9268822/152980675-0461824a-aa05-4b99-90b8-e459b3445164.png">
 
Thank you! 🙏

**Comment by hjdhjd** [comment]
Hi there…and you’re welcome! The very best place to see an example of this library in action is my Homebridge plugin, which this library was originally a part of. :smile:

You can’t “just listen to the websocket”. The data is encoded, largely because of what they’re trying to communicate. You need to use a set of utility functions in this library to decode them.

See:

https://github.com/hjdhjd/homebridge-unifi-protect/blob/2b464fb6b190b7a30c93a5f79abb0b4f754a5a21/src/protect-nvr-events.ts#L153

For an example of how to listen in to events and do useful stuff, including doorbell rings with it.

Enjoy!
